"""
Django settings for portal_config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import dotenv_values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DOTENV = dotenv_values(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DOTENV["SECRET_KEY"]
SECRET_KEY_FALLBACKS = [DOTENV["SECRET_KEY"],]
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
USE_HTTPS = False

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "pet-cam-api.therealsunnyxu.com",
    "pet-cam.therealsunnyxu.com",
    "therealsunnyxu.com",
    "testserver",  # for Django unittest testing
    "django",  # docker, NGINX
]

CORS_ALLOWED_ORIGINS = [
    "https://pet-cam-api.therealsunnyxu.com",  # when deployed
    "https://pet-cam.therealsunnyxu.com",  # when deployed
    "https://therealsunnyxu.com",  # when deployed
    "https://localhost",  # NGINX
    "https://127.0.0.1",  # NGINX
    "http://127.0.0.1:8000",  # running the dev server directly
    "http://localhost:8000",  # running the dev server directly
    "http://django:8000",  # docker, NGINX
    "http://localhost:5173",  # Vite SPA
    "http://127.0.0.1:5173",  # Vite SPA
    "http://localhost:4173",  # Vite SPA
    "http://127.0.0.1:4173",  # Vite SPA
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://pet-cam-api.therealsunnyxu.com",  # when deployed
    "https://pet-cam.therealsunnyxu.com",  # when deployed
    "https://therealsunnyxu.com",  # when deployed
    "https://localhost",  # NGINX
    "https://127.0.0.1",  # NGINX
    "http://127.0.0.1:8000",  # running the dev server directly
    "http://localhost:8000",  # running the dev server directly
    "http://django:8000",  # docker, NGINX
    "http://localhost:5173",  # Vite SPA
    "http://127.0.0.1:5173",  # Vite SPA
    "http://localhost:4173",  # Vite SPA
    "http://127.0.0.1:4173",  # Vite SPA
]
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "auth_api.apps.AuthApiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "portal_config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "portal_config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "test": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "auth_api.User"

MIGRATION_MODULES = {"auth_api": "auth_api.migrations"}

OTP_LENGTH = 6
OTP_EXPIRY_MINUTES = 15
OTP_GRACE_PERIOD_MINUTES = 1

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

FRONTEND_DOMAIN_OVERRIDE = "localhost:5173"
FRONTEND_PASSWORD_RESET_ROUTE = "/reset-password"
PASSWORD_RESET_TIMEOUT = 10 * 60 # seconds?